# Generated by Django 3.0.7 on 2021-10-27 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('first_name', models.CharField(default=' ', max_length=100)),
                ('last_name', models.CharField(default=' ', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('APP USER', 'APP USER'), ('ADMIN', 'ADMIN')], max_length=500, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-id',),
            },
        ),
    ]
